### ISSUE TITLE
Question about theming

### ISSUE THREAD

**Issue by csantos1113** [Temzasse/stitches-native#1]
Hey @Temzasse - First of all, thanks for this project. it looks really nice, pretty light, but strong stitches support from the native side of things. I can't wait to see this library published in `npm`! and tbh I can't wait to see @modulz to work closer with you on having react-native officially supported (cc: 😉 @jonathantneal / @peduarte )

Secondly,
Would it be possible to have semantic tokens defined within the theme definition? Similar to what's in this doc: https://stitches.dev/docs/tokens#token-aliases
```
createCss({
  theme: {
    colors: {
      gray500: 'hsl(206,10%,76%)',
      primary: '$gray500',
    },
  },
});
```

Thanks all

**Comment by Temzasse** [comment]
Hi @csantos1113 👋🏻 

Thanks for bringing this up! I think this should be quite simple to add to the library 👍🏻 

I definitely need to go through the Stitches docs more carefully and figure out what RN feasible features I'm still missing.

**Comment by Temzasse** [comment]
Color aliases are now supported: https://github.com/Temzasse/stitches-native/commit/19b25e86b27f80cca261d9b9a5f3deb13caa3deb

**Comment by csantos-nydig** [comment]
Nice @Temzasse -
Additional qq, Do you have plans to publish this library to `npm` soon?

**Comment by Temzasse** [comment]
@csantos-nydig I can't make any promises but I'll try to get the initial npm release done soon 🤞🏻
