### ISSUE TITLE
Support media css from within utils

### ISSUE THREAD

**Issue by csantos1113** [Temzasse/stitches-native#12]
This is a particular case, yet supported from stitches core where you could make your utils return media css:
```
utils: {
  responsiveStyles: () => (type: 'responsive1' | 'responsive2') => {
    if (type === 'responsive1') {
      return {
        padding: '$1',
        '@large': {
          padding: '$2'
        }
      };
    }
    return {};
  }
}

const Button = styled('div', {
  responsiveStyles: 'responsive1'
});
```

But this is currently not supported by stitches-native.

The idea with this example/code is to enforce a design system pattern, so developers and designers talk in same "system" where the underline values are defined and defined how they adapt to each breakpoint. 
So everywhere else you need a responsive "space" like the example above you only work with `'responsive1'` and that gets translated to the right values for small/medium/large/extraLarge accordingly to what was defined in the "system".
(Instead of the developer having to remember to implement small/medium/large/extraLarge with the correct values on each component to match the values defined in the system)

**Comment by Temzasse** [comment]
@csantos1113 would you have time and bandwidth to make a PR for this? 🙂

**Comment by csantos1113** [comment]
@Temzasse - I unfortunately don't have any time at the moment 😞 . fully consumed in our web app and battling with `@stitches/react` per se 😓. I'll try to find sometime over the weekend, but can't promise anything

**Comment by Temzasse** [comment]
Okay, no worries 👍🏻 I think this is not a very common use case anyway so it's not high on the priority list.

**Comment by Temzasse** [comment]
Closing this as there doesn't seem to be further interest in this feature. Please open a PR if you would like this to be included in Stitches Native 🙂
