### ISSUE TITLE
Tree shaking

### ISSUE THREAD

**Issue by nandorojo** [Temzasse/stitches-native#14]
See my comment at https://github.com/modulz/stitches/issues/596

The styled function shouldn’t accept strings.

**Comment by Temzasse** [comment]
@nandorojo thanks for bringing this up 🙂 

I think staying consistent with the Stitches API is quite important so I'm hesitant to make this kind of a change. 

I'm wondering how other React Native styling libraries handle tree shaking 🤔 It seems that `styled-components` also requires the whole `react-native` but there is [comment](https://github.com/styled-components/styled-components/blob/fde4e44cc9bff71d8e2ed09330a8511d4ef3806f/packages/styled-components/src/native/index.ts#L18) about lazy-requiring that goes beyond my understanding of how React Native internals work.

**Comment by nandorojo** [comment]
Yeah, styled components for native also breaks tree shaking.

**Comment by nandorojo** [comment]
Dripsy has tree shaking enabled. The only way to do so is to build with `expo-module-scripts` rather than `react-native-bob` (I did a lot of research for this for Dripsy).

**Comment by Temzasse** [comment]
I feel like this is not a priority for this project right now especially if tree shaking cannot be achieved with the string based API. I wouldn't want to diverge from the API that the main Stitches lib uses.

I'm gonna close this issue for now but I'm definitely open to continuing the discussion with potential solution ideas 🙂

**Comment by nandorojo** [comment]
Makes sense. In my opinion, this is one of the differences with RN and React DOM — you interact directly with components instead of with markdown-based elements. The ideal situation would be for tree shaking to work, even with strings 🤷‍♂️ oh well, thanks again!

**Comment by nandorojo** [comment]
One other idea: you could have a separate import (like `stitches-native/universal`) which exports all the same stuff, but whose `styled` function _doesn't_ support strings. That way, if you import from there, you only get the tree shaken API. It could work using the `exports` field in `package.json`, similar to `swr/infinite` in the `swr` [library](https://github.com/vercel/swr/blob/master/package.json#L7).
