### ISSUE TITLE
Responsive styles 

### ISSUE THREAD

**Issue by nandorojo** [Temzasse/stitches-native#15]
See my comment at https://github.com/modulz/stitches/issues/596

**Comment by Temzasse** [comment]
@nandorojo thanks for moving the discussion here 🙂 Sorry for not responding earlier. I've been very busy lately so I haven't had much time to work on Stitches Native.

Correct me if I'm wrong but doesn't using [`useWindowDimensions`](https://github.com/Temzasse/stitches-native/blob/1608669ef0fbad6c97d9d7a81ff6db8d3dae4531/src/internals/index.js#L107) mitigate this issue? In the [docs](https://reactnative.dev/docs/usewindowdimensions) it says: 

```
useWindowDimensions automatically updates width and height values when screen size changes.
```

Stitches Native supports two type of media "queries": [device type flags](https://github.com/Temzasse/stitches-native#device-types-based-media-flags) and [device width queries](https://github.com/Temzasse/stitches-native#device-dimensions-based-media-queries).

**Comment by Temzasse** [comment]
@nandorojo did you have time to check my reply? 🙂 I believe responsive styles should work correctly as long as `useWindowDimensions` triggers re-renders when the dimensions change.

**Comment by nandorojo** [comment]
Yes, that should work!

FWIW, in Dripsy, I don’t use window dimensions hook. Instead, I set up a listener for size and only re-render if the breakpoint changes. But this isn’t necessary technically, window dimensions should be sufficient.

**Comment by nandorojo** [comment]
Also, if it interests you, I’ve been working on a React Native hook that allows SSR rendering to work as well, by using CSS media queries on web, and dimensions queries on native. It’s still in the works, but it does seem to work quite well. It’s meant for use inside of design systems, rather than in apps directly.

**Comment by Temzasse** [comment]
@nandorojo I'd be glad to take a look at the hook you mentioned when it's ready 😊 

I'm gonna close this issue for now since responsive styles should work fine in the context of React Native. Having a better support for React Native for Web is probably something that will be tackled once the core is more stable.
