### ISSUE TITLE
Pressable "function style" prop not working when styled is used

### ISSUE THREAD

**Issue by norman-ags** [Temzasse/stitches-native#16]
Title says it all.

Example repo: https://codesandbox.io/s/react-native-web-forked-u12z7?file=/src/App.js:2874-2929

**Comment by Temzasse** [comment]
Fixed in version `0.0.1-4`.

Install it by running `npm install stitches-native@canary`.

**Comment by norman-ags** [comment]
> Fixed in version `0.0.1-4`.
> 
> Install it by running `npm install stitches-native@canary`.

Thanks a lot!
