### ISSUE TITLE
Dynamic styles based on user interaction

### ISSUE THREAD

**Issue by csantos-nydig** [Temzasse/stitches-native#2]
Hey @Temzasse 
I'm looking trough the codebase and I'm wondering what would be the best way to support styles that change dynamically based on user interaction?

https://user-images.githubusercontent.com/87080313/127929311-aab8848f-b666-491a-a25f-110501f962df.mov

**Comment by csantos-nydig** [comment]
Was thinking in maybe exposing the `processStyles` via a react hook where it gets the theme and config internally but receives the given styles via prop. Something like:
```
function useDynamicStyle(css) {
  const t = useTheme();
  return css ? processStyles({
    styles: css || {},
    theme: t.values,
    config
  }) : {};
}

return {
  styled,
  css,
  theme,
  ThemeProvider,
  useDynamicStyle,
  config,
  media: config.media,
  utils: config.utils,
};
```

Usage:
```
const { styled, useDynamicStyle } = createCss({ theme: { colors: { white: '#fff', blue: 'blue' }}});

const StyledPressable = styled('Pressable', {
  backgroundColor: '$white'
});

const pressedStyles = useDynamicStyle(css({
  backgroundColor: '$blue'
}))
<StyledPressable
  style={({ pressed }) => [
    pressed ? pressedStyled : {},
    styles.wrapperCustom
  ]}>
  {({ pressed }) => (
    <Text style={styles.text}>
      {pressed ? 'Pressed!' : 'Press Me'}
    </Text>
  )}
</Pressable>
```

**Comment by csantos-nydig** [comment]
Or would you rather use variants for this... something like

```
const StyledPressable = styled('Pressable', {
  backgroundColor: '$white',
  variants: {
    styl: {
      pressed: {
        backgroundColor: '$blue'
      }
    }
  }
});

const [pressed, setPressed] = useState(false);

<StyledPressable
  styl={pressed ? 'pressed' : undefined}
  onPressIn={() => setPressed(true)}
  onPressOut={() => setPressed(false)}
>
  {({ pressed }) => (
    <Text style={styles.text}>
      {pressed ? 'Pressed!' : 'Press Me'}
    </Text>
  )}
</Pressable>
```

**Comment by Temzasse** [comment]
For your pressed example I would use a boolean variant:

```tsx
const Button = styled('Pressable', {
  // base styles
  variants: {
    pressed: {
      true: {
        backgroundColor: 'red',
      },
      false: {
        backgroundColor: 'blue',
      },
    }
  }
});

<Button pressed={someBooleanValue}>
```

**Comment by Temzasse** [comment]
We definitely need to expose `useTheme` from `createCss` so that theme values can be passed to components that are not stylable via the `styled` API, eg. `ActivityIndicator` has a `color` prop.

**Comment by csantos-nydig** [comment]
> We definitely need to expose `useTheme` from `createCss` so that theme values can be passed to components that are not stylable via the `styled` API, eg. `ActivityIndicator` has a `color` prop.

Yes! Which is why I think we need to expose `processStyles` somehow because those components (eg. `ActivityIndicator`) needs the final/raw values, but I think we should keep theme-access via tokens only
Something like:
```
<ActivityIndicator size="small" color={getRawValue('$colors$blue')} />
// or
<ActivityIndicator size="small" color={processStyles(css({ color: '$blue' })).color} />
```
instead of `useTheme().values.colors.blue`

**Comment by Temzasse** [comment]
I was thinking it would be more straightforward to access the raw values directly from the theme instead of working with theme token names 🤔 

```tsx
const theme = useTheme();

<ActivityIndicator size="small" color={theme.colors.blue} />
```

The exposed `useTheme` can return the `.values` of the internal theme shape directly so the user doesn't need to have to type an extra `.values.x`.

What would be the benefit of working with theme token strings instead of raw theme values?

**Comment by csantos-nydig** [comment]
I was thinking on having us to write styles in the same format regardless of where you need those styles: `css()` / `styled()` / `variants` / `compoundVariants` and inline-styles (like ActivityIndicator.color)

**Comment by Temzasse** [comment]
Linking these two comments here in case they help solving the `useTheme`'s TS issues regarding token aliases.

- [Issue explained](https://github.com/Temzasse/stitches-native/pull/6#discussion_r683260024)
- [Potential solution idea](https://github.com/Temzasse/stitches-native/pull/8#issuecomment-893678766)

**Comment by kg-currenxie** [comment]
Seems `useTheme` is specific to this repo only. Would it make sense to try to implement this into stitches (core) as well? 🤔 I think the web suffers from the same issues (other components that take color props for example)
