### ISSUE TITLE
useTheme returns colors as numbers

### ISSUE THREAD

**Issue by alexaragao** [Temzasse/stitches-native#22]
The type of theme returned when used `useTheme` is different from the `theme` returned by the `createStitches`, see screenshot below:

Type of `theme`:
![theme](https://user-images.githubusercontent.com/43763150/158734285-55f5fcba-ee4b-41a5-a804-2b19a26be908.png)

Type of return of `useTheme`:
![useTheme](https://user-images.githubusercontent.com/43763150/158734287-667185a7-4fe5-4566-8974-db6caf690a89.png)

When `useTheme` hook is called and `theme.colors` is used, the following error occurs:
![error_on_usage](https://user-images.githubusercontent.com/43763150/158734283-97c1a23d-0806-4573-9506-220dfb8df54a.png)

**Comment by Temzasse** [comment]
Fixed in `v0.1.2`.
