### ISSUE TITLE
Any plans to resurrect this?

### ISSUE THREAD

**Issue by lucastobrazil** [Temzasse/stitches-native#48]
Even though stitches is no longer maintained, it was considered "feature complete" - I was wondering with this library if it would be getting upgraded at all or has it been abandoned? I guess because React Native doesn't have as much complexity around web CSS, this is still a pretty neat way to organise styles and get the power of stitches variants etc :-)

**Comment by Temzasse** [comment]
Hi @lucastobrazil 👋🏻 

I really would like to resurrect this project and I actually had this #44 PR that I never was able to fully get done 😅 

On the Web side I've been transitioning to [Panda CSS](https://panda-css.com/) and I have been wondering if I should pivot this library to `panda-native` instead as Panda CSS has very similar API design as Stitches and the project is not dead 🤔 

I will probably work on this library (or `panda-native`) when I have my next mobile app project at work. Currently I'm very busy with Web stuff.

**Comment by lucastobrazil** [comment]
No worries! Yeah it dawned on me that the only stitches "dependency" is the types, which IMO are still really powerful.

For context, we have Design system built for react web that uses stitches, and have decided that we will focus on having a consistent API between Web and native in the short term until we decide on a plan for migrating away from stitches completely. 

This project has been super helpful to be able to maintain the same API across platforms!
