### ISSUE TITLE
API changes - stitches 1.0

### ISSUE THREAD

**Issue by csantos1113** [Temzasse/stitches-native#9]
Just a heads up. good to keep eyes on the changes stitches.dev is including in its 1.0 release: https://github.com/modulz/stitches/projects/4

There are quite a lot of API changes we would like to consider/include to stitches-native 👀

**Comment by Temzasse** [comment]
Thanks for the heads up 👍🏻 It might be good to wait until v1 ships before we release `stitches-native` to npm. Otherwise we would have to make a lot of breaking changes immediately after the release 😅

**Comment by Temzasse** [comment]
Woop woop [Stitches v1](https://twitter.com/stitchesjs/status/1432388594245767180?s=21) is finally here 🎉 

I think now we should go ahead and try to get the initial release of Stitches Native out. I already updated the core API a few weeks ago but I need to check if something has changed after that.

One big thing that I would like to get done is to get the new improved TS types copied over and modified to work with RN.

I probably don't have much free time this week but I might have more time next week to work on this project.

@csantos-nydig and @finkef would you like to help me gather all the major todo items that we still have to implement for the initial release? 😊

**Comment by Temzasse** [comment]
I have now updated the TS types to reflect the latest Stitches v1 types (check this [commit](https://github.com/Temzasse/stitches-native/commit/616ea133346dfc2f8b895c86964230dc1cb40903) if you want to see the changes).

I still need to double check that the internals implement the whole new Stitches API 🤞🏻

I'll close this issue for now and we can open new more specific issues if needed.

Next I'm going to check that the build setup with [react-native-builder-bob](https://github.com/callstack/react-native-builder-bob) is working correctly for npm and publish a few [canary releases](https://www.npmjs.com/package/stitches-native) for further testing.

**Comment by csantos1113** [comment]
Great news @Temzasse - I'm sorry I haven't have time to collaborate, but we're still here! 👀 !!
